{
"beagle" : "/cluster/home/nkadri/PROGRAMS/BEAGLE5.4/beagle.22Jul22.46e.jar ",
"OUT_DIR" : "/cluster/work/pausch/naveen/RECOMBINATION",
"plink" : "/cluster/work/pausch/group_bin/plink ",
"gcta" : "/cluster/home/nkadri/PROGRAMS/GCTA/gcta-1.94.1-linux-kernel-3-x86_64/gcta-1.94.1 "
}
